//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaveApplication.AddNewEmployee {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    
    
    public partial class AddNewEmployee {
        
        protected global::System.Web.UI.WebControls.Label lb1;
        
        protected global::System.Web.UI.WebControls.TextBox txtempid;
        
        protected global::System.Web.UI.WebControls.Label Label1;
        
        protected global::Microsoft.SharePoint.WebControls.PeopleEditor peoplepickeremp;
        
        protected global::System.Web.UI.WebControls.Label Label2;
        
        protected global::System.Web.UI.WebControls.TextBox txtfristname;
        
        protected global::System.Web.UI.WebControls.Label Label3;
        
        protected global::System.Web.UI.WebControls.TextBox txtlastname;
        
        protected global::System.Web.UI.WebControls.Label Label4;
        
        protected global::System.Web.UI.WebControls.DropDownList DdlEmptype;
        
        protected global::System.Web.UI.WebControls.Label Label5;
        
        protected global::System.Web.UI.WebControls.DropDownList DdlDep;
        
        protected global::System.Web.UI.WebControls.Label Label6;
        
        protected global::System.Web.UI.WebControls.DropDownList DdlDesignation;
        
        protected global::System.Web.UI.WebControls.Label Label7;
        
        protected global::System.Web.UI.WebControls.DropDownList ddlReportingTo;
        
        protected global::System.Web.UI.WebControls.Label Label8;
        
        protected global::System.Web.UI.WebControls.Label lbldoj;
        
        protected global::Microsoft.SharePoint.WebControls.DateTimeControl DtDoj;
        
        protected global::System.Web.UI.WebControls.Label Label9;
        
        protected global::Microsoft.SharePoint.WebControls.DateTimeControl DtDOP;
        
        protected global::System.Web.UI.HtmlControls.HtmlTableRow divdop;
        
        protected global::System.Web.UI.WebControls.Label LblError;
        
        protected global::System.Web.UI.WebControls.HiddenField hdnCurrentYear;
        
        protected global::System.Web.UI.WebControls.HiddenField hdnStrtFnclMnth;
        
        protected global::System.Web.UI.WebControls.Button BtnRegister;
        
        protected global::System.Web.UI.WebControls.Button BtnCancel;
        
        public static implicit operator global::System.Web.UI.TemplateControl(AddNewEmployee target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControllb1() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.lb1 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lb1";
            @__ctrl.Text = "*";
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtempid() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txtempid = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txtempid";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControlLabel1() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.Label1 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "Label1";
            @__ctrl.Text = "*";
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::Microsoft.SharePoint.WebControls.PeopleEditor @__BuildControlpeoplepickeremp() {
            global::Microsoft.SharePoint.WebControls.PeopleEditor @__ctrl;
            @__ctrl = new global::Microsoft.SharePoint.WebControls.PeopleEditor();
            this.peoplepickeremp = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "peoplepickeremp";
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(355D, global::System.Web.UI.WebControls.UnitType.Pixel);
            @__ctrl.Visible = true;
            @__ctrl.AllowEmpty = false;
            @__ctrl.ValidatorEnabled = true;
            @__ctrl.SelectionSet = "User";
            @__ctrl.MultiSelect = false;
            @__ctrl.CssClass = "NoBorder";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControlLabel2() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.Label2 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "Label2";
            @__ctrl.Text = "*";
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtfristname() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txtfristname = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txtfristname";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControlLabel3() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.Label3 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "Label3";
            @__ctrl.Text = "*";
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtlastname() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txtlastname = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txtlastname";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControlLabel4() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.Label4 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "Label4";
            @__ctrl.Text = "*";
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControlDdlEmptype() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            this.DdlEmptype = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "DdlEmptype";
            @__ctrl.AutoPostBack = false;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControlLabel5() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.Label5 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "Label5";
            @__ctrl.Text = "*";
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControlDdlDep() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            this.DdlDep = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "DdlDep";
            @__ctrl.AutoPostBack = false;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControlLabel6() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.Label6 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "Label6";
            @__ctrl.Text = "*";
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControlDdlDesignation() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            this.DdlDesignation = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "DdlDesignation";
            @__ctrl.AutoPostBack = false;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControlLabel7() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.Label7 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "Label7";
            @__ctrl.Text = "*";
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControlddlReportingTo() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            this.ddlReportingTo = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "ddlReportingTo";
            @__ctrl.AutoPostBack = false;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControlLabel8() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.Label8 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "Label8";
            @__ctrl.Text = "*";
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControllbldoj() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.lbldoj = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lbldoj";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::Microsoft.SharePoint.WebControls.DateTimeControl @__BuildControlDtDoj() {
            global::Microsoft.SharePoint.WebControls.DateTimeControl @__ctrl;
            @__ctrl = new global::Microsoft.SharePoint.WebControls.DateTimeControl();
            this.DtDoj = @__ctrl;
            @__ctrl.ID = "DtDoj";
            @__ctrl.DateOnly = true;
            @__ctrl.MaxDate = new System.DateTime(3000, 12, 31, 0, 0, 0, 0);
            @__ctrl.LocaleId = 1033;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControlLabel9() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.Label9 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "Label9";
            @__ctrl.Text = "*";
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlTableCell @__BuildControl__control3() {
            global::System.Web.UI.HtmlControls.HtmlTableCell @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlTableCell("td");
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                <label>\r\n                    Date of Permanent (MM/DD/YYYY)</la" +
                        "bel>\r\n                "));
            global::System.Web.UI.WebControls.Label @__ctrl1;
            @__ctrl1 = this.@__BuildControlLabel9();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n            "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::Microsoft.SharePoint.WebControls.DateTimeControl @__BuildControlDtDOP() {
            global::Microsoft.SharePoint.WebControls.DateTimeControl @__ctrl;
            @__ctrl = new global::Microsoft.SharePoint.WebControls.DateTimeControl();
            this.DtDOP = @__ctrl;
            @__ctrl.ID = "DtDOP";
            @__ctrl.DateOnly = true;
            @__ctrl.MaxDate = new System.DateTime(3000, 12, 31, 0, 0, 0, 0);
            @__ctrl.LocaleId = 1033;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlTableCell @__BuildControl__control4() {
            global::System.Web.UI.HtmlControls.HtmlTableCell @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlTableCell("td");
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "NoBorder");
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                "));
            global::Microsoft.SharePoint.WebControls.DateTimeControl @__ctrl1;
            @__ctrl1 = this.@__BuildControlDtDOP();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n            "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control2(System.Web.UI.HtmlControls.HtmlTableCellCollection @__ctrl) {
            global::System.Web.UI.HtmlControls.HtmlTableCell @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control3();
            @__ctrl.Add(@__ctrl1);
            global::System.Web.UI.HtmlControls.HtmlTableCell @__ctrl2;
            @__ctrl2 = this.@__BuildControl__control4();
            @__ctrl.Add(@__ctrl2);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlTableRow @__BuildControldivdop() {
            global::System.Web.UI.HtmlControls.HtmlTableRow @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlTableRow();
            this.divdop = @__ctrl;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "data");
            @__ctrl.ID = "divdop";
            this.@__BuildControl__control2(@__ctrl.Cells);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControlLblError() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.LblError = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "LblError";
            @__ctrl.CssClass = "ErrorInfo";
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.HiddenField @__BuildControlhdnCurrentYear() {
            global::System.Web.UI.WebControls.HiddenField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.HiddenField();
            this.hdnCurrentYear = @__ctrl;
            @__ctrl.ID = "hdnCurrentYear";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.HiddenField @__BuildControlhdnStrtFnclMnth() {
            global::System.Web.UI.WebControls.HiddenField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.HiddenField();
            this.hdnStrtFnclMnth = @__ctrl;
            @__ctrl.ID = "hdnStrtFnclMnth";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Button @__BuildControlBtnRegister() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.BtnRegister = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.Text = "Submit";
            @__ctrl.ID = "BtnRegister";
            @__ctrl.ValidationGroup = "save";
            @__ctrl.Click -= new System.EventHandler(this.BtnRegisterClick);
            @__ctrl.Click += new System.EventHandler(this.BtnRegisterClick);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Button @__BuildControlBtnCancel() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.BtnCancel = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.Text = "Reset";
            @__ctrl.ID = "BtnCancel";
            @__ctrl.Click -= new System.EventHandler(this.BtnResetClick);
            @__ctrl.Click += new System.EventHandler(this.BtnResetClick);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControlTree(global::LeaveApplication.AddNewEmployee.AddNewEmployee @__ctrl) {
            global::System.Web.UI.WebControls.Label @__ctrl1;
            @__ctrl1 = this.@__BuildControllb1();
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(@__ctrl1);
            global::System.Web.UI.WebControls.TextBox @__ctrl2;
            @__ctrl2 = this.@__BuildControltxtempid();
            @__parser.AddParsedSubObject(@__ctrl2);
            global::System.Web.UI.WebControls.Label @__ctrl3;
            @__ctrl3 = this.@__BuildControlLabel1();
            @__parser.AddParsedSubObject(@__ctrl3);
            global::Microsoft.SharePoint.WebControls.PeopleEditor @__ctrl4;
            @__ctrl4 = this.@__BuildControlpeoplepickeremp();
            @__parser.AddParsedSubObject(@__ctrl4);
            global::System.Web.UI.WebControls.Label @__ctrl5;
            @__ctrl5 = this.@__BuildControlLabel2();
            @__parser.AddParsedSubObject(@__ctrl5);
            global::System.Web.UI.WebControls.TextBox @__ctrl6;
            @__ctrl6 = this.@__BuildControltxtfristname();
            @__parser.AddParsedSubObject(@__ctrl6);
            global::System.Web.UI.WebControls.Label @__ctrl7;
            @__ctrl7 = this.@__BuildControlLabel3();
            @__parser.AddParsedSubObject(@__ctrl7);
            global::System.Web.UI.WebControls.TextBox @__ctrl8;
            @__ctrl8 = this.@__BuildControltxtlastname();
            @__parser.AddParsedSubObject(@__ctrl8);
            global::System.Web.UI.WebControls.Label @__ctrl9;
            @__ctrl9 = this.@__BuildControlLabel4();
            @__parser.AddParsedSubObject(@__ctrl9);
            global::System.Web.UI.WebControls.DropDownList @__ctrl10;
            @__ctrl10 = this.@__BuildControlDdlEmptype();
            @__parser.AddParsedSubObject(@__ctrl10);
            global::System.Web.UI.WebControls.Label @__ctrl11;
            @__ctrl11 = this.@__BuildControlLabel5();
            @__parser.AddParsedSubObject(@__ctrl11);
            global::System.Web.UI.WebControls.DropDownList @__ctrl12;
            @__ctrl12 = this.@__BuildControlDdlDep();
            @__parser.AddParsedSubObject(@__ctrl12);
            global::System.Web.UI.WebControls.Label @__ctrl13;
            @__ctrl13 = this.@__BuildControlLabel6();
            @__parser.AddParsedSubObject(@__ctrl13);
            global::System.Web.UI.WebControls.DropDownList @__ctrl14;
            @__ctrl14 = this.@__BuildControlDdlDesignation();
            @__parser.AddParsedSubObject(@__ctrl14);
            global::System.Web.UI.WebControls.Label @__ctrl15;
            @__ctrl15 = this.@__BuildControlLabel7();
            @__parser.AddParsedSubObject(@__ctrl15);
            global::System.Web.UI.WebControls.DropDownList @__ctrl16;
            @__ctrl16 = this.@__BuildControlddlReportingTo();
            @__parser.AddParsedSubObject(@__ctrl16);
            global::System.Web.UI.WebControls.Label @__ctrl17;
            @__ctrl17 = this.@__BuildControlLabel8();
            @__parser.AddParsedSubObject(@__ctrl17);
            global::System.Web.UI.WebControls.Label @__ctrl18;
            @__ctrl18 = this.@__BuildControllbldoj();
            @__parser.AddParsedSubObject(@__ctrl18);
            global::Microsoft.SharePoint.WebControls.DateTimeControl @__ctrl19;
            @__ctrl19 = this.@__BuildControlDtDoj();
            @__parser.AddParsedSubObject(@__ctrl19);
            global::System.Web.UI.HtmlControls.HtmlTableRow @__ctrl20;
            @__ctrl20 = this.@__BuildControldivdop();
            @__parser.AddParsedSubObject(@__ctrl20);
            global::System.Web.UI.WebControls.Label @__ctrl21;
            @__ctrl21 = this.@__BuildControlLblError();
            @__parser.AddParsedSubObject(@__ctrl21);
            global::System.Web.UI.WebControls.HiddenField @__ctrl22;
            @__ctrl22 = this.@__BuildControlhdnCurrentYear();
            @__parser.AddParsedSubObject(@__ctrl22);
            global::System.Web.UI.WebControls.HiddenField @__ctrl23;
            @__ctrl23 = this.@__BuildControlhdnStrtFnclMnth();
            @__parser.AddParsedSubObject(@__ctrl23);
            global::System.Web.UI.WebControls.Button @__ctrl24;
            @__ctrl24 = this.@__BuildControlBtnRegister();
            @__parser.AddParsedSubObject(@__ctrl24);
            global::System.Web.UI.WebControls.Button @__ctrl25;
            @__ctrl25 = this.@__BuildControlBtnCancel();
            @__parser.AddParsedSubObject(@__ctrl25);
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__Render__control1));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__Render__control1(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            @__w.Write(@"
<link href=""../_layouts/15/LeaveApplication/StyleSheet.css"" rel=""stylesheet"" />
<script src=""../_layouts/15/LeaveApplication/jquery.min.js""></script>


<script lang=""javascript"" type=""text/javascript"">
    $(document).ready(function () {
        hideOrVisibleDivdop($.trim($('#");
                               @__w.Write( DdlEmptype.ClientID );

            @__w.Write("\').val()));\r\n        $(\'#");
    @__w.Write( DdlEmptype.ClientID );

            @__w.Write("\').change(function () {\r\n            hideOrVisibleDivdop($.trim($(this).val()));\r" +
                    "\n        });\r\n        function hideOrVisibleDivdop(selectedValue) {\r\n           " +
                    " if (selectedValue == \"Permanent\") {\r\n                $(\'#");
            @__w.Write( divdop.ClientID );

            @__w.Write("\').show();\r\n            } else {\r\n                $(\'#");
            @__w.Write( divdop.ClientID );

            @__w.Write(@"').hide();
            }
        }
    });
</script>

<div class=""Container"">
    <table>
        <tr class=""header""> 
            <th colspan=""2"">
                <h3>
                    Please enter the following details.</h3>
            </th>
        </tr>
        <tr class=""data"">
            <td>
                <label>
                    Employee Id</label>
                ");
            parameterContainer.Controls[0].RenderControl(@__w);
            @__w.Write("\r\n            </td>\r\n            <td>\r\n                ");
            parameterContainer.Controls[1].RenderControl(@__w);
            @__w.Write("\r\n                \r\n            </td>\r\n        </tr>\r\n        <tr class=\"data\">\r\n" +
                    "            <td>\r\n                <label>\r\n                    Employee Name</la" +
                    "bel>\r\n                ");
            parameterContainer.Controls[2].RenderControl(@__w);
            @__w.Write("\r\n            </td>\r\n            <td>\r\n                ");
            parameterContainer.Controls[3].RenderControl(@__w);
            @__w.Write("\r\n\r\n            </td>\r\n        </tr>\r\n        <tr class=\"data\">\r\n            <td>" +
                    "\r\n                <label>\r\n                    First Name</label>\r\n             " +
                    "   ");
            parameterContainer.Controls[4].RenderControl(@__w);
            @__w.Write("\r\n\r\n            </td>\r\n            <td>\r\n                ");
            parameterContainer.Controls[5].RenderControl(@__w);
            @__w.Write("\r\n               \r\n            </td>\r\n        </tr>\r\n        <tr class=\"data\">\r\n " +
                    "           <td>\r\n                <label>\r\n                    Last Name</label>\r" +
                    "\n                ");
            parameterContainer.Controls[6].RenderControl(@__w);
            @__w.Write("\r\n            </td>\r\n            <td>\r\n                ");
            parameterContainer.Controls[7].RenderControl(@__w);
            @__w.Write("\r\n              \r\n            </td>\r\n        </tr>\r\n        <tr class=\"data\">\r\n  " +
                    "          <td>\r\n                <label>\r\n                    Employee Type</labe" +
                    "l>\r\n                ");
            parameterContainer.Controls[8].RenderControl(@__w);
            @__w.Write("\r\n            </td>\r\n            <td>\r\n                ");
            parameterContainer.Controls[9].RenderControl(@__w);
            @__w.Write("\r\n            </td>\r\n        </tr>\r\n        <tr class=\"data\">\r\n            <td>\r\n" +
                    "                <label>\r\n                    Department</label>\r\n               " +
                    " ");
            parameterContainer.Controls[10].RenderControl(@__w);
            @__w.Write("\r\n            </td>\r\n            <td>\r\n                ");
            parameterContainer.Controls[11].RenderControl(@__w);
            @__w.Write("\r\n            </td>\r\n        </tr>\r\n        <tr class=\"data\">\r\n            <td>\r\n" +
                    "                <label>\r\n                    Designation</label>\r\n              " +
                    "  ");
            parameterContainer.Controls[12].RenderControl(@__w);
            @__w.Write("\r\n            </td>\r\n            <td>\r\n                ");
            parameterContainer.Controls[13].RenderControl(@__w);
            @__w.Write("\r\n            </td>\r\n        </tr>\r\n        <tr class=\"data\">\r\n            <td>\r\n" +
                    "                <label>\r\n                    Reporting To</label>\r\n             " +
                    "   ");
            parameterContainer.Controls[14].RenderControl(@__w);
            @__w.Write("\r\n            </td>\r\n            <td>\r\n                ");
            parameterContainer.Controls[15].RenderControl(@__w);
            @__w.Write("\r\n            </td>\r\n        </tr>\r\n        \r\n        \r\n        \r\n        <tr cla" +
                    "ss=\"data\">\r\n            <td>\r\n                <label>\r\n                    Date " +
                    "of Join (MM/DD/YYYY)</label>\r\n                ");
            parameterContainer.Controls[16].RenderControl(@__w);
            @__w.Write("\r\n            \r\n            </td>\r\n            <td class=\"NoBorder\">\r\n           " +
                    "     ");
            parameterContainer.Controls[17].RenderControl(@__w);
            @__w.Write("\r\n                ");
            parameterContainer.Controls[18].RenderControl(@__w);
            @__w.Write("\r\n            </td>\r\n        </tr>\r\n        ");
            parameterContainer.Controls[19].RenderControl(@__w);
            @__w.Write("\r\n        ");
           if (!string.IsNullOrEmpty(LblError.Text.Trim()))
           {
            @__w.Write("\r\n        <tr class=\"data\">\r\n            <td colspan=\"2\">\r\n                ");
            parameterContainer.Controls[20].RenderControl(@__w);
            @__w.Write("\r\n            </td>\r\n        </tr>\r\n        ");
           } 
            @__w.Write("\r\n        <tr class=\"controls\">\r\n            <td class=\"noborders\">\r\n            " +
                    "    \r\n                ");
            parameterContainer.Controls[21].RenderControl(@__w);
            @__w.Write("\r\n                ");
            parameterContainer.Controls[22].RenderControl(@__w);
            @__w.Write("\r\n            </td>\r\n            <td class=\"noborders\">\r\n                ");
            parameterContainer.Controls[23].RenderControl(@__w);
            @__w.Write("\r\n                ");
            parameterContainer.Controls[24].RenderControl(@__w);
            @__w.Write("\r\n            </td>\r\n        </tr>\r\n    </table>\r\n</div>");
        }
        
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
