//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaveApplication.UpdateEmployeeLeaves {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    
    
    public partial class UpdateEmployeeLeaves {
        
        protected global::System.Web.UI.WebControls.Button btbolreset;
        
        protected global::System.Web.UI.WebControls.Button btnnewupdate;
        
        protected global::System.Web.UI.WebControls.Button btnprobationary;
        
        protected global::System.Web.UI.WebControls.Button btnnewviewreport;
        
        protected global::System.Web.UI.WebControls.Label lblupdation;
        
        protected global::System.Web.UI.WebControls.HiddenField hdnCurrentYear;
        
        protected global::System.Web.UI.WebControls.HiddenField hdnUpdatingMonth;
        
        protected global::System.Web.UI.WebControls.HiddenField hdnoptionalmonth;
        
        protected global::System.Web.UI.WebControls.HiddenField hdnprobupdating;
        
        protected global::System.Web.UI.WebControls.HiddenField hdnupdated;
        
        protected global::System.Web.UI.WebControls.HiddenField hdnOLUpdate;
        
        protected global::System.Web.UI.WebControls.Label lblError;
        
        protected global::System.Web.UI.WebControls.Label lblErr;
        
        public static implicit operator global::System.Web.UI.TemplateControl(UpdateEmployeeLeaves target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtbolreset() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.btbolreset = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "btbolreset";
            @__ctrl.Text = "Update Optional Leave";
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(167D, global::System.Web.UI.WebControls.UnitType.Pixel);
            @__ctrl.Click -= new System.EventHandler(this.BtnOLresetClick);
            @__ctrl.Click += new System.EventHandler(this.BtnOLresetClick);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnnewupdate() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.btnnewupdate = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "btnnewupdate";
            @__ctrl.Text = "Update PL for Permanent";
            @__ctrl.Click -= new System.EventHandler(this.btnnewupdate_Click);
            @__ctrl.Click += new System.EventHandler(this.btnnewupdate_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnprobationary() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.btnprobationary = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "btnprobationary";
            @__ctrl.Text = "Update PL for Probationary";
            @__ctrl.Click -= new System.EventHandler(this.btnprobationary_Click);
            @__ctrl.Click += new System.EventHandler(this.btnprobationary_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnnewviewreport() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.btnnewviewreport = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "btnnewviewreport";
            @__ctrl.Text = "View Leave Status";
            @__ctrl.Click -= new System.EventHandler(this.btnnewviewreport_Click);
            @__ctrl.Click += new System.EventHandler(this.btnnewviewreport_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControllblupdation() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.lblupdation = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lblupdation";
            @__ctrl.Text = "Updation Status";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.HiddenField @__BuildControlhdnCurrentYear() {
            global::System.Web.UI.WebControls.HiddenField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.HiddenField();
            this.hdnCurrentYear = @__ctrl;
            @__ctrl.ID = "hdnCurrentYear";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.HiddenField @__BuildControlhdnUpdatingMonth() {
            global::System.Web.UI.WebControls.HiddenField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.HiddenField();
            this.hdnUpdatingMonth = @__ctrl;
            @__ctrl.ID = "hdnUpdatingMonth";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.HiddenField @__BuildControlhdnoptionalmonth() {
            global::System.Web.UI.WebControls.HiddenField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.HiddenField();
            this.hdnoptionalmonth = @__ctrl;
            @__ctrl.ID = "hdnoptionalmonth";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.HiddenField @__BuildControlhdnprobupdating() {
            global::System.Web.UI.WebControls.HiddenField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.HiddenField();
            this.hdnprobupdating = @__ctrl;
            @__ctrl.ID = "hdnprobupdating";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.HiddenField @__BuildControlhdnupdated() {
            global::System.Web.UI.WebControls.HiddenField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.HiddenField();
            this.hdnupdated = @__ctrl;
            @__ctrl.ID = "hdnupdated";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.HiddenField @__BuildControlhdnOLUpdate() {
            global::System.Web.UI.WebControls.HiddenField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.HiddenField();
            this.hdnOLUpdate = @__ctrl;
            @__ctrl.ID = "hdnOLUpdate";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControllblError() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.lblError = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lblError";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControllblErr() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.lblErr = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lblErr";
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControlTree(global::LeaveApplication.UpdateEmployeeLeaves.UpdateEmployeeLeaves @__ctrl) {
            global::System.Web.UI.WebControls.Button @__ctrl1;
            @__ctrl1 = this.@__BuildControlbtbolreset();
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(@__ctrl1);
            global::System.Web.UI.WebControls.Button @__ctrl2;
            @__ctrl2 = this.@__BuildControlbtnnewupdate();
            @__parser.AddParsedSubObject(@__ctrl2);
            global::System.Web.UI.WebControls.Button @__ctrl3;
            @__ctrl3 = this.@__BuildControlbtnprobationary();
            @__parser.AddParsedSubObject(@__ctrl3);
            global::System.Web.UI.WebControls.Button @__ctrl4;
            @__ctrl4 = this.@__BuildControlbtnnewviewreport();
            @__parser.AddParsedSubObject(@__ctrl4);
            global::System.Web.UI.WebControls.Label @__ctrl5;
            @__ctrl5 = this.@__BuildControllblupdation();
            @__parser.AddParsedSubObject(@__ctrl5);
            global::System.Web.UI.WebControls.HiddenField @__ctrl6;
            @__ctrl6 = this.@__BuildControlhdnCurrentYear();
            @__parser.AddParsedSubObject(@__ctrl6);
            global::System.Web.UI.WebControls.HiddenField @__ctrl7;
            @__ctrl7 = this.@__BuildControlhdnUpdatingMonth();
            @__parser.AddParsedSubObject(@__ctrl7);
            global::System.Web.UI.WebControls.HiddenField @__ctrl8;
            @__ctrl8 = this.@__BuildControlhdnoptionalmonth();
            @__parser.AddParsedSubObject(@__ctrl8);
            global::System.Web.UI.WebControls.HiddenField @__ctrl9;
            @__ctrl9 = this.@__BuildControlhdnprobupdating();
            @__parser.AddParsedSubObject(@__ctrl9);
            global::System.Web.UI.WebControls.HiddenField @__ctrl10;
            @__ctrl10 = this.@__BuildControlhdnupdated();
            @__parser.AddParsedSubObject(@__ctrl10);
            global::System.Web.UI.WebControls.HiddenField @__ctrl11;
            @__ctrl11 = this.@__BuildControlhdnOLUpdate();
            @__parser.AddParsedSubObject(@__ctrl11);
            global::System.Web.UI.WebControls.Label @__ctrl12;
            @__ctrl12 = this.@__BuildControllblError();
            @__parser.AddParsedSubObject(@__ctrl12);
            global::System.Web.UI.WebControls.Label @__ctrl13;
            @__ctrl13 = this.@__BuildControllblErr();
            @__parser.AddParsedSubObject(@__ctrl13);
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__Render__control1));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__Render__control1(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            @__w.Write("\r\n<link href=\"../_layouts/15/LeaveApplication/StyleSheet.css\" rel=\"stylesheet\" />" +
                    "\r\n\r\n\r\n");
            parameterContainer.Controls[0].RenderControl(@__w);
            @__w.Write("\r\n\r\n\r\n\r\n");
            parameterContainer.Controls[1].RenderControl(@__w);
            @__w.Write("\r\n\r\n");
            parameterContainer.Controls[2].RenderControl(@__w);
            @__w.Write("\r\n");
            parameterContainer.Controls[3].RenderControl(@__w);
            @__w.Write("\r\n\r\n\r\n\r\n");
            parameterContainer.Controls[4].RenderControl(@__w);
            @__w.Write("\r\n");
            parameterContainer.Controls[5].RenderControl(@__w);
            @__w.Write("\r\n");
            parameterContainer.Controls[6].RenderControl(@__w);
            @__w.Write("\r\n");
            parameterContainer.Controls[7].RenderControl(@__w);
            @__w.Write("\r\n");
            parameterContainer.Controls[8].RenderControl(@__w);
            @__w.Write("\r\n");
            parameterContainer.Controls[9].RenderControl(@__w);
            @__w.Write("\r\n\r\n\r\n");
            parameterContainer.Controls[10].RenderControl(@__w);
            @__w.Write("\r\n");
            parameterContainer.Controls[11].RenderControl(@__w);
            @__w.Write("\r\n");
   System.Data.DataTable result = ViewState["Result"] as System.Data.DataTable;

   if (result != null && result.Rows.Count > 0)
   {

            @__w.Write("\r\n<div class=\"Container\">\r\n    <table>\r\n        <tr class=\"header\">\r\n            " +
                    "");
               foreach (System.Data.DataColumn column in result.Columns)
               { 
                   if (column.ColumnName != "TempEmployeeName" && column.ColumnName != "TempReportingTo")
                   {
            @__w.Write("\r\n            <th>\r\n                ");
        @__w.Write( column.ColumnName );

            @__w.Write("\r\n            </th>\r\n            ");
               }
               } 
            @__w.Write("\r\n        </tr>\r\n        ");
           foreach (System.Data.DataRow row in result.Rows)
           {
            @__w.Write("\r\n        <tr class=\"data\">\r\n            ");
               foreach (System.Data.DataColumn column in result.Columns)
               {
                   if (column.ColumnName != "TempEmployeeName" && column.ColumnName != "TempReportingTo")
                   {
            @__w.Write("\r\n            <td>\r\n                ");
        @__w.Write( row[column.ColumnName].ToString() );

            @__w.Write("\r\n            </td>\r\n            ");
               }
               }
            @__w.Write("\r\n        </tr>\r\n        ");
           } 
            @__w.Write("\r\n    </table>\r\n</div>\r\n");
   }
   else
   { 
            @__w.Write("\r\n<div class=\"Container\">\r\n    <table>\r\n        <tr class=\"data\">\r\n            <t" +
                    "d colspan=\"2\">\r\n                ");
            parameterContainer.Controls[12].RenderControl(@__w);
            @__w.Write("\r\n            </td>\r\n        </tr>\r\n        <tr class=\"header\">\r\n            <th>" +
                    "\r\n                There is no records.\r\n            </th>\r\n        </tr>\r\n    </" +
                    "table>\r\n</div>\r\n");
   } 
            @__w.Write("<br />\r\n<br />\r\n");
   System.Data.DataTable pendingResult = ViewState["PendingResult"] as System.Data.DataTable;

   if (pendingResult != null && pendingResult.Rows.Count > 0)
   {

            @__w.Write("\r\n<div class=\"Container\">\r\n    <table>\r\n        <tr class=\"header\">\r\n            " +
                    "");
               foreach (System.Data.DataColumn column in pendingResult.Columns)
               {
            @__w.Write("\r\n            <th>\r\n                ");
        @__w.Write(column.ColumnName );

            @__w.Write("\r\n            </th>\r\n            ");
               } 
            @__w.Write("\r\n        </tr>\r\n        ");
           foreach (System.Data.DataRow row in pendingResult.Rows)
           {
            @__w.Write("\r\n        <tr class=\"data\">\r\n            ");
               foreach (System.Data.DataColumn column in pendingResult.Columns)
               {
            @__w.Write("\r\n            <td>\r\n                ");
        @__w.Write( row[column.ColumnName].ToString() );

            @__w.Write("\r\n            </td>\r\n            ");
               } 
            @__w.Write("\r\n        </tr>\r\n        ");
           } 
            @__w.Write("\r\n    </table>\r\n</div>\r\n");
   } 
            @__w.Write("<br />\r\n<br />\r\n");
        }
        
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
